#! /usr/bin/env python3
import re
from numpy import *

definition = '''/** @file sat_lindal92.cpp"
  *
  * This file is automatically generated by make_sa_lindal92.py
  *
  * @author Cheng Li
  */

#include "sat_lindal92.hpp"

namespace Saturn {
  int const lindal92_num = <num>;
  double const lindal92_T[<num>] = {
    <T_array>
  };
  // pressure in bars
  double const lindal92_P[<num>] = {
    <P_array>
  };
}
'''

declaration = '''#ifndef SAT_LINDAL92_HPP
#define SAT_LINDAL02_HPP

/** @file sat_lindal92.hpp"
  *
  * This file is automatically generated by make_sat_lindal92.py
  *
  * @author Cheng Li
  */
namespace Saturn {
  extern int const lindal92_num;
  extern double const lindal92_T[];
  extern double const lindal92_P[];
}

#endif
'''
  
data = genfromtxt('lindal_sat_inv.dat', comments = '#', dtype = str)
num = len(data)
Tarray = ',\n    '.join(data[:,1])
Parray = ',\n    '.join(data[:,0])
definition = re.sub('<num>', str(num), definition)
definition = re.sub('<T_array>', Tarray, definition)
definition = re.sub('<P_array>', Parray, definition)

with open('sat_lindal92.cpp', 'w') as file:
  file.write(definition)
with open('sat_lindal92.hpp', 'w') as file:
  file.write(declaration)
